services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mag-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: bitnami/postgresql:latest
    container_name: mag-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kJ2nWndf29f!@xs
      - POSTGRES_DB=dbmag
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mag-prisma
    command: ["npx", "prisma", "migrate", "deploy"]
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
